"""update_assistants_and_documents

Revision ID: 0f486d76726d
Revises: a1b2c3d4e5f6
Create Date: 2026-06-06 09:11:35.578067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f486d76726d'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index('ix_assistants_tenant_id', table_name='assistants')
    op.create_index('idx_assistants_tenant', 'assistants', ['tenant_id'], unique=False)
    op.alter_column('documents', 'assistant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_documents_assistant', 'documents', ['assistant_id'], unique=False)
    op.create_unique_constraint('uq_documents_assistant_filename', 'documents', ['assistant_id', 'filename'])
    op.drop_constraint('documents_assistant_id_fkey', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'assistants', ['assistant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_assistant_id_fkey', 'documents', 'assistants', ['assistant_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_documents_assistant_filename', 'documents', type_='unique')
    op.drop_index('idx_documents_assistant', table_name='documents')
    op.alter_column('documents', 'assistant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_assistants_tenant', table_name='assistants')
    op.create_index('ix_assistants_tenant_id', 'assistants', ['tenant_id'], unique=False)
    op.drop_column('assistants', 'updated_at')
    # ### end Alembic commands ###
